package com.indo.game.mapper.es;

import java.util.List;

import com.indo.game.pojo.entity.es.EsBetOrder;
import com.indo.game.pojo.entity.es.EsBetOrderExample;
import org.apache.ibatis.annotations.Param;

public interface EsBetOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    int countByExample(EsBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    int deleteByExample(EsBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    int insert(EsBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    int insertSelective(EsBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    EsBetOrder selectOneByExample(EsBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    List<EsBetOrder> selectByExample(EsBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    EsBetOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EsBetOrder record, @Param("example") EsBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EsBetOrder record, @Param("example") EsBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EsBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table es_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EsBetOrder record);
}