package com.indo.game.pojo.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
@Data
@TableName("cpt_open_member")
public class CptOpenMember implements Serializable {
    /**
     * 字段: cpt_open_member.id<br/>
     * 主键: 自动增长<br/>
     * 必填: true<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 
     *
     * @mbggenerated
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;

    /**
     * 字段: cpt_open_member.user_id<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: CPT用户uid
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * 字段: cpt_open_member.username<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第三方登入账号(随机生成)
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * 字段: cpt_open_member.password<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 255<br/>
     * 说明: 第三方登入密码(随机生成)
     *
     * @mbggenerated
     */
    private String password;

    /**
     * 字段: cpt_open_member.balance<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 第三方余额（元）
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * 字段: cpt_open_member.type<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 10<br/>
     * 说明: 账号类型()
     *
     * @mbggenerated
     */
    private String type;

    /**
     * 字段: cpt_open_member.create_time<br/>
     * 必填: true<br/>
     * 缺省: CURRENT_TIMESTAMP<br/>
     * 长度: 19<br/>
     * 说明: 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 字段: cpt_open_member.login_time<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 19<br/>
     * 说明: 登入时间
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * 字段: cpt_open_member.layer_no<br/>
     * 必填: false<br/>
     * 缺省: <br/>
     * 长度: 20<br/>
     * 说明: 用户分层编号（代理扩展）
     *
     * @mbggenerated
     */
    private String layerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cpt_open_member
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

}