package com.indo.game.mapper.ae;

import java.util.List;

import com.indo.game.pojo.entity.ae.AeBetOrder;
import com.indo.game.pojo.entity.ae.AeBetOrderExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AeBetOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order`
     *
     * @mbggenerated
     */
    int countByExample(AeBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    int deleteByExample(AeBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    int insert(AeBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    int insertSelective(AeBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    AeBetOrder selectOneByExampleWithBLOBs(AeBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    List<AeBetOrder> selectByExampleWithBLOBs(AeBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    AeBetOrder selectOneByExample(AeBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    List<AeBetOrder> selectByExample(AeBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    AeBetOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AeBetOrder record, @Param("example") AeBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") AeBetOrder record, @Param("example") AeBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AeBetOrder record, @Param("example") AeBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AeBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(AeBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AeBetOrder record);
}