package com.indo.game.mapper.ae;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.indo.game.pojo.entity.ae.AeGame;
import com.indo.game.pojo.entity.ae.AeGameExample;
import org.apache.ibatis.annotations.Param;

public interface AeGameMapper extends BaseMapper<AeGame> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    int countByExample(AeGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    int deleteByExample(AeGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    int insert(AeGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    int insertSelective(AeGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    AeGame selectOneByExample(AeGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    List<AeGame> selectByExample(AeGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    AeGame selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AeGame record, @Param("example") AeGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AeGame record, @Param("example") AeGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AeGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_game
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AeGame record);
}