package com.indo.game.mapper.ae;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.indo.game.pojo.entity.ae.AeRoom;
import com.indo.game.pojo.entity.ae.AeRoomExample;
import org.apache.ibatis.annotations.Param;

public interface AeRoomMapper extends BaseMapper<AeRoom> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    int countByExample(AeRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    int deleteByExample(AeRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    int insert(AeRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    int insertSelective(AeRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    AeRoom selectOneByExample(AeRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    List<AeRoom> selectByExample(AeRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    AeRoom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AeRoom record, @Param("example") AeRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AeRoom record, @Param("example") AeRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AeRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_room
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AeRoom record);
}