package com.indo.game.mapper.ag;

import java.util.List;

import com.indo.game.pojo.entity.ag.AgFishBetOrder;
import com.indo.game.pojo.entity.ag.AgFishBetOrderExample;
import org.apache.ibatis.annotations.Param;

public interface AgFishBetOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    int countByExample(AgFishBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    int deleteByExample(AgFishBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    int insert(AgFishBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    int insertSelective(AgFishBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    AgFishBetOrder selectOneByExample(AgFishBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    List<AgFishBetOrder> selectByExample(AgFishBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    AgFishBetOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AgFishBetOrder record, @Param("example") AgFishBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AgFishBetOrder record, @Param("example") AgFishBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AgFishBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_fish_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AgFishBetOrder record);
}