package com.indo.game.mapper;

import java.util.List;

import com.indo.game.pojo.entity.GameBetamountRecord;
import com.indo.game.pojo.entity.GameBetamountRecordExample;
import org.apache.ibatis.annotations.Param;

public interface GameBetamountRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    int countByExample(GameBetamountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    int deleteByExample(GameBetamountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    int insert(GameBetamountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    int insertSelective(GameBetamountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    GameBetamountRecord selectOneByExample(GameBetamountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    List<GameBetamountRecord> selectByExample(GameBetamountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    GameBetamountRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GameBetamountRecord record, @Param("example") GameBetamountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GameBetamountRecord record, @Param("example") GameBetamountRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GameBetamountRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_betamount_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GameBetamountRecord record);
}