package com.indo.game.mapper;

import java.util.List;

import com.indo.game.pojo.entity.MemBaseinfoExample;
import com.indo.user.pojo.entity.MemBaseinfo;
import org.apache.ibatis.annotations.Param;

public interface MemBaseinfoMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_baseinfo
//     *
//     * @mbggenerated
//     */
//    int countByExample(MemBaseinfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_baseinfo
//     *
//     * @mbggenerated
//     */
//    int deleteByExample(MemBaseinfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_baseinfo
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Long memid);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_baseinfo
//     *
//     * @mbggenerated
//     */
//    int insert(MemBaseinfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_baseinfo
//     *
//     * @mbggenerated
//     */
//    int insertSelective(MemBaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_baseinfo
     *
     * @mbggenerated
     */
    MemBaseinfo selectOneByExample(MemBaseinfoExample example);

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_baseinfo
//     *
//     * @mbggenerated
//     */
//    List<MemBaseinfo> selectByExample(MemBaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_baseinfo
     *
     * @mbggenerated
     */
    MemBaseinfo selectByPrimaryKey(Long memid);

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_baseinfo
//     *
//     * @mbggenerated
//     */
//    int updateByExampleSelective(@Param("record") MemBaseinfo record, @Param("example") MemBaseinfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_baseinfo
//     *
//     * @mbggenerated
//     */
//    int updateByExample(@Param("record") MemBaseinfo record, @Param("example") MemBaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_baseinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemBaseinfo record);

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_baseinfo
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(MemBaseinfo record);
}