package com.indo.game.mapper;

import java.util.List;

import com.indo.game.pojo.entity.MemGoldchange;
import org.apache.ibatis.annotations.Param;

public interface MemGoldchangeMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    int countByExample(MemGoldchangeExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    int deleteByExample(MemGoldchangeExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Long goldchangid);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    int insert(MemGoldchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_goldchange
     *
     * @mbggenerated
     */
    int insertSelective(MemGoldchange record);

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    MemGoldchange selectOneByExample(MemGoldchangeExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    List<MemGoldchange> selectByExample(MemGoldchangeExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    MemGoldchange selectByPrimaryKey(Long goldchangid);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    int updateByExampleSelective(@Param("record") MemGoldchange record, @Param("example") MemGoldchangeExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    int updateByExample(@Param("record") MemGoldchange record, @Param("example") MemGoldchangeExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKeySelective(MemGoldchange record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mem_goldchange
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(MemGoldchange record);
}