package com.indo.game.mapper;

import java.math.BigDecimal;
import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.indo.game.pojo.entity.SysChessBalance;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SysChessBalanceMapper  extends BaseMapper<SysChessBalance> {
    /**
     * 增加额度(下分)
     * @param chessCode
     * @param balance
     * @return
     */
    int addBalance(@Param("chessCode") String chessCode,@Param("balance") BigDecimal balance);


    /**
     * 减去额度（上分）
     * @param chessCode
     * @param balance
     * @return
     */
    int subtractBalance(@Param("chessCode") String chessCode,@Param("balance") BigDecimal balance);

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    int countByExample(SysChessBalanceExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    int deleteByExample(SysChessBalanceExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Long id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    int insert(SysChessBalance record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    int insertSelective(SysChessBalance record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    SysChessBalance selectOneByExample(SysChessBalanceExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    List<SysChessBalance> selectByExample(SysChessBalanceExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    SysChessBalance selectByPrimaryKey(Long id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    int updateByExampleSelective(@Param("record") SysChessBalance record, @Param("example") SysChessBalanceExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    int updateByExample(@Param("record") SysChessBalance record, @Param("example") SysChessBalanceExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKeySelective(SysChessBalance record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_chess_balance
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(SysChessBalance record);
}