package com.indo.game.mapper.ky;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.indo.game.pojo.entity.ky.KyKind;
import com.indo.game.pojo.entity.ky.KyKindExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface KyKindMapper  extends BaseMapper<KyKindMapper> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    int countByExample(KyKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    int deleteByExample(KyKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    int insert(KyKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    int insertSelective(KyKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    KyKind selectOneByExample(KyKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    List<KyKind> selectByExample(KyKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    KyKind selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") KyKind record, @Param("example") KyKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") KyKind record, @Param("example") KyKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KyKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ky_kind
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KyKind record);
}