package com.indo.game.mapper.mg;

import java.util.List;

import com.indo.game.pojo.entity.mg.MgBetOrder;
import com.indo.game.pojo.entity.mg.MgBetOrderExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface MgBetOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    int countByExample(MgBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    int deleteByExample(MgBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    int insert(MgBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    int insertSelective(MgBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    MgBetOrder selectOneByExample(MgBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    List<MgBetOrder> selectByExample(MgBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    MgBetOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MgBetOrder record, @Param("example") MgBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MgBetOrder record, @Param("example") MgBetOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MgBetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_bet_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MgBetOrder record);
}